[phases.setup]
nixPkgs = ["python311", "libGL", "libglib"]

[phases.install]
cmds = ["pip install -r aeronet/server/requirements.txt"]

[start]
cmd = "cd aeronet/server && uvicorn app:app --host 0.0.0.0 --port $PORT"
